// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:6b3f2fed-40d0-41af-a889-ded4a08e7e32",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_dNWijDPgP",
    "aws_user_pools_web_client_id": "5vrk0d6jk58ma4bj626eeej85s"
};


export default awsmobile;
